version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: exam_paper_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - exam-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: exam_paper_server
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://root:example@mongodb:27017/exam_paper_creator?authSource=admin
      - JWT_SECRET=your_jwt_secret_here
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - exam-network
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: exam_paper_client
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - exam-network
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  mongodb_data:

networks:
  exam-network:
    driver: bridge